-- copy/sed/paste on the output of monodevelop's assembly browser

ffi = require "ffi"

ffi.cdef[[
enum { GameTagSTATE = 204, GameTagTURN = 20, GameTagSTEP = 19, GameTagNEXT_STEP = 198, GameTagTEAM_ID = 31, GameTagPLAYER_ID = 30, GameTagSTARTHANDSIZE = 29, GameTagMAXHANDSIZE = 28, GameTagMAXRESOURCES = 176, GameTagTIMEOUT = 7, GameTagTURN_START, GameTagTURN_TIMER_SLUSH, GameTagGOLD_REWARD_STATE = 13, GameTagFIRST_PLAYER = 24, GameTagCURRENT_PLAYER = 23, GameTagHERO_ENTITY = 27, GameTagRESOURCES = 26, GameTagRESOURCES_USED = 25, GameTagFATIGUE = 22, GameTagPLAYSTATE = 17, GameTagCURRENT_SPELLPOWER = 291, GameTagMULLIGAN_STATE = 305, GameTagHAND_REVEALED = 348, GameTagSTEADY_SHOT_CAN_TARGET = 383, GameTagCARDNAME = 185, GameTagCARDTEXT_INHAND = 184, GameTagCARDRACE = 200, GameTagCARDTYPE = 202, GameTagCOST = 48, GameTagHEALTH = 45, GameTagATK = 47, GameTagDURABILITY = 187, GameTagARMOR = 292, GameTagPREDAMAGE = 318, GameTagTARGETING_ARROW_TEXT = 325, GameTagLAST_AFFECTED_BY = 18, GameTagENCHANTMENT_BIRTH_VISUAL = 330, GameTagENCHANTMENT_IDLE_VISUAL, GameTagPREMIUM = 12, GameTagIGNORE_DAMAGE = 1, GameTagIGNORE_DAMAGE_OFF = 354, GameTagENTITY_ID = 53, GameTagDEFINITION = 52, GameTagOWNER = 51, GameTagCONTROLLER = 50, GameTagZONE = 49, GameTagEXHAUSTED = 43, GameTagATTACHED = 40, GameTagPROPOSED_ATTACKER = 39, GameTagATTACKING = 38, GameTagPROPOSED_DEFENDER = 37, GameTagDEFENDING = 36, GameTagPROTECTED = 35, GameTagPROTECTING = 34, GameTagRECENTLY_ARRIVED = 33, GameTagDAMAGE = 44, GameTagTRIGGER_VISUAL = 32, GameTagTAUNT = 190, GameTagSPELLPOWER = 192, GameTagDIVINE_SHIELD = 194, GameTagCHARGE = 197, GameTagSECRET = 219, GameTagMORPH = 293, GameTagTAUNT_READY = 306, GameTagSTEALTH_READY, GameTagCHARGE_READY, GameTagCREATOR = 313, GameTagCANT_DRAW = 232, GameTagCANT_PLAY = 231, GameTagCANT_DISCARD = 230, GameTagCANT_DESTROY = 229, GameTagCANT_TARGET = 228, GameTagCANT_ATTACK = 227, GameTagCANT_EXHAUST = 226, GameTagCANT_READY = 225, GameTagCANT_REMOVE_FROM_GAME = 224, GameTagCANT_SET_ASIDE = 223, GameTagCANT_DAMAGE = 222, GameTagCANT_HEAL = 221, GameTagCANT_BE_DESTROYED = 247, GameTagCANT_BE_TARGETED = 246, GameTagCANT_BE_ATTACKED = 245, GameTagCANT_BE_EXHAUSTED = 244, GameTagCANT_BE_READIED = 243, GameTagCANT_BE_REMOVED_FROM_GAME = 242, GameTagCANT_BE_SET_ASIDE = 241, GameTagCANT_BE_DAMAGED = 240, GameTagCANT_BE_HEALED = 239, GameTagCANT_BE_SUMMONING_SICK = 253, GameTagCANT_BE_DISPELLED = 314, GameTagINCOMING_DAMAGE_CAP = 238, GameTagINCOMING_DAMAGE_ADJUSTMENT = 237, GameTagINCOMING_DAMAGE_MULTIPLIER = 236, GameTagINCOMING_HEALING_CAP = 235, GameTagINCOMING_HEALING_ADJUSTMENT = 234, GameTagINCOMING_HEALING_MULTIPLIER = 233, GameTagFROZEN = 260, GameTagJUST_PLAYED, GameTagLINKEDCARD, GameTagZONE_POSITION, GameTagCANT_BE_FROZEN, GameTagCOMBO_ACTIVE = 266, GameTagCARD_TARGET, GameTagNUM_CARDS_PLAYED_THIS_TURN = 269, GameTagCANT_BE_TARGETED_BY_OPPONENTS, GameTagNUM_TURNS_IN_PLAY, GameTagSUMMONED = 205, GameTagENRAGED = 212, GameTagSILENCED = 188, GameTagWINDFURY, GameTagLOYALTY = 216, GameTagDEATHRATTLE, GameTagADJACENT_BUFF = 350, GameTagSTEALTH = 191, GameTagBATTLECRY = 218, GameTagNUM_TURNS_LEFT = 272, GameTagOUTGOING_DAMAGE_CAP, GameTagOUTGOING_DAMAGE_ADJUSTMENT, GameTagOUTGOING_DAMAGE_MULTIPLIER, GameTagOUTGOING_HEALING_CAP, GameTagOUTGOING_HEALING_ADJUSTMENT, GameTagOUTGOING_HEALING_MULTIPLIER, GameTagINCOMING_ABILITY_DAMAGE_ADJUSTMENT, GameTagINCOMING_COMBAT_DAMAGE_ADJUSTMENT, GameTagOUTGOING_ABILITY_DAMAGE_ADJUSTMENT, GameTagOUTGOING_COMBAT_DAMAGE_ADJUSTMENT, GameTagOUTGOING_ABILITY_DAMAGE_MULTIPLIER, GameTagOUTGOING_ABILITY_DAMAGE_CAP, GameTagINCOMING_ABILITY_DAMAGE_MULTIPLIER, GameTagINCOMING_ABILITY_DAMAGE_CAP, GameTagOUTGOING_COMBAT_DAMAGE_MULTIPLIER, GameTagOUTGOING_COMBAT_DAMAGE_CAP, GameTagINCOMING_COMBAT_DAMAGE_MULTIPLIER, GameTagINCOMING_COMBAT_DAMAGE_CAP, GameTagIS_MORPHED = 294, GameTagTEMP_RESOURCES, GameTagRECALL_OWED, GameTagNUM_ATTACKS_THIS_TURN, GameTagNEXT_ALLY_BUFF = 302, GameTagMAGNET, GameTagFIRST_CARD_PLAYED_THIS_TURN, GameTagCARD_ID = 186, GameTagCANT_BE_TARGETED_BY_ABILITIES = 311, GameTagSHOULDEXITCOMBAT, GameTagPARENT_CARD = 316, GameTagNUM_MINIONS_PLAYED_THIS_TURN, GameTagCANT_BE_TARGETED_BY_HERO_POWERS = 332, GameTagCANT_BE_TARGETED_BY_BATTLECRIES = 379, GameTagCOMBO = 220, GameTagELITE = 114, GameTagCARD_SET = 183, GameTagFACTION = 201, GameTagRARITY = 203, GameTagCLASS = 199, GameTagMISSION_EVENT = 6, GameTagFREEZE = 208, GameTagRECALL = 215, GameTagSILENCE = 339, GameTagCOUNTER, GameTagARTISTNAME = 342, GameTagFLAVORTEXT = 351, GameTagFORCED_PLAY, GameTagLOW_HEALTH_THRESHOLD, GameTagSPELLPOWER_DOUBLE = 356, GameTagHEALING_DOUBLE, GameTagNUM_OPTIONS_PLAYED_THIS_TURN, GameTagNUM_OPTIONS, GameTagTO_BE_DESTROYED, GameTagHEALTH_MINIMUM = 337, GameTagAURA = 362, GameTagPOISONOUS, GameTagHOW_TO_EARN, GameTagHOW_TO_EARN_GOLDEN, GameTagTAG_HERO_POWER_DOUBLE, GameTagTAG_AI_MUST_PLAY, GameTagNUM_MINIONS_PLAYER_KILLED_THIS_TURN, GameTagNUM_MINIONS_KILLED_THIS_TURN, GameTagAFFECTED_BY_SPELL_POWER, GameTagEXTRA_DEATHRATTLES, GameTagSTART_WITH_1_HEALTH, GameTagIMMUNE_WHILE_ATTACKING, GameTagMULTIPLY_HERO_DAMAGE, GameTagMULTIPLY_BUFF_VALUE, GameTagCUSTOM_KEYWORD_EFFECT, GameTagTOPDECK, GameTagSHOWN_HERO_POWER = 380, GameTagDEATHRATTLE_SENDS_BACK_TO_DECK = 382, GameTagDISPLAYED_CREATOR = 385, GameTagPOWERED_UP, GameTagSPARE_PART = 388, GameTagFORGETFUL, GameTagCAN_SUMMON_MAXPLUSONE_MINION, GameTagOBFUSCATED, GameTagBURNING, GameTagOVERLOAD_LOCKED, GameTagNUM_TIMES_HERO_POWER_USED_THIS_GAME, GameTagCURRENT_HEROPOWER_DAMAGE_BONUS, GameTagHEROPOWER_DAMAGE, GameTagLAST_CARD_PLAYED, GameTagNUM_FRIENDLY_MINIONS_THAT_DIED_THIS_TURN, GameTagNUM_CARDS_DRAWN_THIS_TURN, GameTagAI_ONE_SHOT_KILL, GameTagEVIL_GLOW, GameTagHIDE_COST };
enum { PowerHistoryKindFULL_ENTITY = 1, PowerHistoryKindSHOW_ENTITY, PowerHistoryKindHIDE_ENTITY, PowerHistoryKindTAG_CHANGE, PowerHistoryKindCREATE_GAME, PowerHistoryKindPOWER_START, PowerHistoryKindPOWER_END, PowerHistoryKindMETA_DATA };
enum { PLAYSTATEINVALID, PLAYSTATEPLAYING, PLAYSTATEWINNING, PLAYSTATELOSING, PLAYSTATEWON, PLAYSTATELOST, PLAYSTATETIED, PLAYSTATEDISCONNECTED, PLAYSTATEQUIT };
enum { STEPINVALID, STEPBEGIN_FIRST, STEPBEGIN_SHUFFLE, STEPBEGIN_DRAW, STEPBEGIN_MULLIGAN, STEPMAIN_BEGIN, STEPMAIN_READY, STEPMAIN_RESOURCE, STEPMAIN_DRAW, STEPMAIN_START, STEPMAIN_ACTION, STEPMAIN_COMBAT, STEPMAIN_END, STEPMAIN_NEXT, STEPFINAL_WRAPUP, STEPFINAL_GAMEOVER, STEPMAIN_CLEANUP, STEPMAIN_START_TRIGGERS };
enum { STATEINVALID, STATELOADING, STATERUNNING, STATECOMPLETE };
enum { CARDTYPEINVALID, CARDTYPEGAME, CARDTYPEPLAYER, CARDTYPEHERO, CARDTYPEMINION, CARDTYPEABILITY, CARDTYPEENCHANTMENT, CARDTYPEWEAPON, CARDTYPEITEM, CARDTYPETOKEN, CARDTYPEHERO_POWER };
enum { RARITYINVALID, RARITYCOMMON, RARITYFREE, RARITYRARE, RARITYEPIC, RARITYLEGENDARY };
enum { ZONEINVALID, ZONEPLAY, ZONEDECK, ZONEHAND, ZONEGRAVEYARD, ZONEREMOVEDFROMGAME, ZONESETASIDE, ZONESECRET };
enum { MULLIGANINVALID, MULLIGANINPUT, MULLIGANDEALING, MULLIGANWAITING, MULLIGANDONE };
enum { ENCHANTMENT_VISUALINVALID, ENCHANTMENT_VISUALPOSITIVE, ENCHANTMENT_VISUALNEGATIVE, ENCHANTMENT_VISUALNEUTRAL };
enum { FACTIONINVALID, FACTIONHORDE, FACTIONALLIANCE, FACTIONNEUTRAL };
]]

enums =
	PowerHistoryKind: {
		"FULL_ENTITY", "SHOW_ENTITY", "HIDE_ENTITY", "TAG_CHANGE", "CREATE_GAME", "POWER_START", "POWER_END", "META_DATA"
	}
	GameTag: {
		"STATE", "TURN", "STEP", "NEXT_STEP", "TEAM_ID", "PLAYER_ID", "STARTHANDSIZE", "MAXHANDSIZE", "MAXRESOURCES", "TIMEOUT", "TURN_START", "TURN_TIMER_SLUSH", "GOLD_REWARD_STATE", "FIRST_PLAYER", "CURRENT_PLAYER", "HERO_ENTITY", "RESOURCES", "RESOURCES_USED", "FATIGUE", "PLAYSTATE", "CURRENT_SPELLPOWER", "MULLIGAN_STATE", "HAND_REVEALED", "STEADY_SHOT_CAN_TARGET", "CARDNAME", "CARDTEXT_INHAND", "CARDRACE", "CARDTYPE", "COST", "HEALTH", "ATK", "DURABILITY", "ARMOR", "PREDAMAGE", "TARGETING_ARROW_TEXT", "LAST_AFFECTED_BY", "ENCHANTMENT_BIRTH_VISUAL", "ENCHANTMENT_IDLE_VISUAL", "PREMIUM", "IGNORE_DAMAGE", "IGNORE_DAMAGE_OFF", "ENTITY_ID", "DEFINITION", "OWNER", "CONTROLLER", "ZONE", "EXHAUSTED", "ATTACHED", "PROPOSED_ATTACKER", "ATTACKING", "PROPOSED_DEFENDER", "DEFENDING", "PROTECTED", "PROTECTING", "RECENTLY_ARRIVED", "DAMAGE", "TRIGGER_VISUAL", "TAUNT", "SPELLPOWER", "DIVINE_SHIELD", "CHARGE", "SECRET", "MORPH", "TAUNT_READY", "STEALTH_READY", "CHARGE_READY", "CREATOR", "CANT_DRAW", "CANT_PLAY", "CANT_DISCARD", "CANT_DESTROY", "CANT_TARGET", "CANT_ATTACK", "CANT_EXHAUST", "CANT_READY", "CANT_REMOVE_FROM_GAME", "CANT_SET_ASIDE", "CANT_DAMAGE", "CANT_HEAL", "CANT_BE_DESTROYED", "CANT_BE_TARGETED", "CANT_BE_ATTACKED", "CANT_BE_EXHAUSTED", "CANT_BE_READIED", "CANT_BE_REMOVED_FROM_GAME", "CANT_BE_SET_ASIDE", "CANT_BE_DAMAGED", "CANT_BE_HEALED", "CANT_BE_SUMMONING_SICK", "CANT_BE_DISPELLED", "INCOMING_DAMAGE_CAP", "INCOMING_DAMAGE_ADJUSTMENT", "INCOMING_DAMAGE_MULTIPLIER", "INCOMING_HEALING_CAP", "INCOMING_HEALING_ADJUSTMENT", "INCOMING_HEALING_MULTIPLIER", "FROZEN", "JUST_PLAYED", "LINKEDCARD", "ZONE_POSITION", "CANT_BE_FROZEN", "COMBO_ACTIVE", "CARD_TARGET", "NUM_CARDS_PLAYED_THIS_TURN", "CANT_BE_TARGETED_BY_OPPONENTS", "NUM_TURNS_IN_PLAY", "SUMMONED", "ENRAGED", "SILENCED", "WINDFURY", "LOYALTY", "DEATHRATTLE", "ADJACENT_BUFF", "STEALTH", "BATTLECRY", "NUM_TURNS_LEFT", "OUTGOING_DAMAGE_CAP", "OUTGOING_DAMAGE_ADJUSTMENT", "OUTGOING_DAMAGE_MULTIPLIER", "OUTGOING_HEALING_CAP", "OUTGOING_HEALING_ADJUSTMENT", "OUTGOING_HEALING_MULTIPLIER", "INCOMING_ABILITY_DAMAGE_ADJUSTMENT", "INCOMING_COMBAT_DAMAGE_ADJUSTMENT", "OUTGOING_ABILITY_DAMAGE_ADJUSTMENT", "OUTGOING_COMBAT_DAMAGE_ADJUSTMENT", "OUTGOING_ABILITY_DAMAGE_MULTIPLIER", "OUTGOING_ABILITY_DAMAGE_CAP", "INCOMING_ABILITY_DAMAGE_MULTIPLIER", "INCOMING_ABILITY_DAMAGE_CAP", "OUTGOING_COMBAT_DAMAGE_MULTIPLIER", "OUTGOING_COMBAT_DAMAGE_CAP", "INCOMING_COMBAT_DAMAGE_MULTIPLIER", "INCOMING_COMBAT_DAMAGE_CAP", "IS_MORPHED", "TEMP_RESOURCES", "RECALL_OWED", "NUM_ATTACKS_THIS_TURN", "NEXT_ALLY_BUFF", "MAGNET", "FIRST_CARD_PLAYED_THIS_TURN", "CARD_ID", "CANT_BE_TARGETED_BY_ABILITIES", "SHOULDEXITCOMBAT", "PARENT_CARD", "NUM_MINIONS_PLAYED_THIS_TURN", "CANT_BE_TARGETED_BY_HERO_POWERS", "CANT_BE_TARGETED_BY_BATTLECRIES", "COMBO", "ELITE", "CARD_SET", "FACTION", "RARITY", "CLASS", "MISSION_EVENT", "FREEZE", "RECALL", "SILENCE", "COUNTER", "ARTISTNAME", "FLAVORTEXT", "FORCED_PLAY", "LOW_HEALTH_THRESHOLD", "SPELLPOWER_DOUBLE", "HEALING_DOUBLE", "NUM_OPTIONS_PLAYED_THIS_TURN", "NUM_OPTIONS", "TO_BE_DESTROYED", "HEALTH_MINIMUM", "AURA", "POISONOUS", "HOW_TO_EARN", "HOW_TO_EARN_GOLDEN", "TAG_HERO_POWER_DOUBLE", "TAG_AI_MUST_PLAY", "NUM_MINIONS_PLAYER_KILLED_THIS_TURN", "NUM_MINIONS_KILLED_THIS_TURN", "AFFECTED_BY_SPELL_POWER", "EXTRA_DEATHRATTLES", "START_WITH_1_HEALTH", "IMMUNE_WHILE_ATTACKING", "MULTIPLY_HERO_DAMAGE", "MULTIPLY_BUFF_VALUE", "CUSTOM_KEYWORD_EFFECT", "TOPDECK", "SHOWN_HERO_POWER", "DEATHRATTLE_SENDS_BACK_TO_DECK", "DISPLAYED_CREATOR", "POWERED_UP", "SPARE_PART", "FORGETFUL", "CAN_SUMMON_MAXPLUSONE_MINION", "OBFUSCATED", "BURNING", "OVERLOAD_LOCKED", "NUM_TIMES_HERO_POWER_USED_THIS_GAME", "CURRENT_HEROPOWER_DAMAGE_BONUS", "HEROPOWER_DAMAGE", "LAST_CARD_PLAYED", "NUM_FRIENDLY_MINIONS_THAT_DIED_THIS_TURN", "NUM_CARDS_DRAWN_THIS_TURN", "AI_ONE_SHOT_KILL", "EVIL_GLOW", "HIDE_COST"
	}
	PLAYSTATE: {
		"INVALID", "PLAYING", "WINNING", "LOSING", "WON", "LOST", "TIED", "DISCONNECTED", "QUIT"
	}
	STEP: {
		"INVALID", "BEGIN_FIRST", "BEGIN_SHUFFLE", "BEGIN_DRAW", "BEGIN_MULLIGAN", "MAIN_BEGIN", "MAIN_READY", "MAIN_RESOURCE", "MAIN_DRAW", "MAIN_START", "MAIN_ACTION", "MAIN_COMBAT", "MAIN_END", "MAIN_NEXT", "FINAL_WRAPUP", "FINAL_GAMEOVER", "MAIN_CLEANUP", "MAIN_START_TRIGGERS"
	}
	STATE: {
		"INVALID", "LOADING", "RUNNING", "COMPLETE"
	}
	CARDTYPE: {
		"INVALID", "GAME", "PLAYER", "HERO", "MINION", "ABILITY", "ENCHANTMENT", "WEAPON", "ITEM", "TOKEN", "HERO_POWER"
	}
	RARITY: {
		"INVALID", "COMMON", "FREE", "RARE", "EPIC", "LEGENDARY"
	}
	ZONE: {
		"INVALID", "PLAY", "DECK", "HAND", "GRAVEYARD", "REMOVEDFROMGAME", "SETASIDE", "SECRET"
	}
	MULLIGAN: {
		"INVALID", "INPUT", "DEALING", "WAITING", "DONE"
	}
	ENCHANTMENT_VISUAL: {
		"INVALID", "POSITIVE", "NEGATIVE", "NEUTRAL"
	}
	FACTION: {
		"INVALID", "HORDE", "ALLIANCE", "NEUTRAL"
	}

enum_values = do
	result = {}
	for name, strings in pairs enums
		result[name] = {}
		for str in *strings
			result[name][str] = ffi.C[name .. str]
	result

enum_names = do
	result = {}
	for name, strings in pairs enums
		result[name] = {}
		for str in *strings
			result[name][ffi.C[name .. str]] = str
	result

return { :enums, :enum_values, :enum_names }